axiom-crypto/openvm-reth-benchmark

- .github/workflows/update-patches.yml
- .gitignore
example PR made with this workflow: https://github.com/axiom-crypto/openvm-reth-benchmark/pull/34
> fix: patch workflow

- .cargo/config.template.toml
- .cargo/config.toml
Something is still not renamed
> [fix] Finish renaming stuff after macro renaming

- bin/host/src/main.rs
> feat: Mode to run execute and generate

- .github/workflows/reth-benchmark.yml
- .github/workflows/update-patches.yml
> feat(ci): add bencher metrics, flamegraphs, and cron job for benchmarks

- .github/workflows/reth-benchmark.yml
- .github/workflows/update-patches.yml
- bin/host/src/main.rs
- benchmark name separates by mode, block number
- cron job always uses `nightly` branch (and force pushes)
> chore: update CI for bencher

- .github/workflows/reth-benchmark.yml
> chore(ci): use profile maxperf lto=fat

- .github/workflows/compare-bench.yml
- .github/workflows/reth-benchmark.yml
- .github/workflows/update-patches.yml
c7a.48xlarge has enough memory
> chore(ci): add more details to step summary, switch to c7a

- .github/workflows/compare-bench.yml
- .github/workflows/reth-benchmark.yml
- .github/workflows/update-patches.yml
> chore(ci): change default instance to m8g.24xlarge

- bin/host/src/main.rs
- crates/executor/host/tests/integration.rs
This pull request contains changes to improve clarity, correctness and structure.
> fix: typos in documentation files

- Cargo.lock
- Cargo.toml
- bin/client-eth/Cargo.lock
- bin/client-eth/Cargo.toml
openvm, revm, openvm-kzg commits all updated
> chore: update dependencies

- .github/workflows/update-patches.yml
> chore: fix workflows

- .gitignore
- Cargo.lock
- Cargo.toml
- bin/host/Cargo.toml
- bin/host/src/main.rs
Added a retry/backoff layer to try and retry on rpc http errors
> fix: retry on rpc errors

- .cargo/config.local.toml
- .cargo/config.toml
- Cargo.lock
- Cargo.toml
- crates/host-bench/Cargo.toml
- crates/host-bench/src/lib.rs
- run.sh
- updates references of `openvm-benchmarks` to `openvm-benchmarks-prove`
> chore: update openvm rev to a10f050

- .github/workflows/reth-benchmark.yml
- Cargo.lock
- Cargo.toml
- crates/host-bench/src/lib.rs
merge after https://github.com/openvm-org/openvm/pull/1570 
closes INT-3302
> feat: add Aggregation Tree Configuration

- Cargo.lock
- Cargo.toml
- crates/host-bench/src/lib.rs
`ContinuationProver` is renamed to `EvmHalo2Prover`
> fix: openvm SDK renaming

- .github/workflows/reth-benchmark.yml
- crates/host-bench/src/lib.rs
closes INT-3816
```
gh workflow run .github/workflows/reth-benchmark.yml --ref feat/custom-segmentation -f segment_max_cells=1200000000
```
https://github.com/axiom-crypto/openvm-reth-benchmark/actions/runs/14426946176
> feat: custom segmentation strategy by total cell count

- .github/workflows/compare-bench.yml
- .github/workflows/reth-benchmark.yml
Add build flags and feature flags to the host binary cache key
> fix: CI binary cache key

- Cargo.lock
- Cargo.toml
- bin/client-eth/Cargo.lock
- crates/executor/client/src/io.rs
- crates/mpt/src/lib.rs
https://github.com/axiom-crypto/openvm-reth-benchmark/actions/runs/14801460641
> chore: bump openvm and bincode

- crates/executor/client/src/io.rs
We check the state root against a trusted state root, but we missed this check on storage roots. This PR fixes this bug by checking storage trie roots against account storage roots, which are stored and constrain in the state trie.
> fix: constrain storage roots

- .github/workflows/reth-benchmark.yml
- Cargo.lock
- README.md
- bin/client-eth/Cargo.lock
- crates/host-bench/src/lib.rs
- run.sh
> feat(new-execution): update to use new sdk interface

- crates/mpt/src/mpt/build_mpt.rs
Fixes out-of-bound errors in `cached_references` while building MPT on block 21926929.
The `shorten_node_path_arena` function created new temporary MPT arenas when processing exclusion proofs. If it encountered an `Extension` node, it would copy the `child_id` from the original arena into the new one without duplicating the actual child subtree. This created a dangling `NodeId` that was invalid in the context of the new, smaller arena, leading to an out-of-bounds access when the temporary trie was later processed.
This PR fixes the issue by making a copy of a child subtree's arena. It's probably not the most optimal solution but it's not important as it's on the host side.
Tested with integration test on block 21926929 with QuickNode.
[Bench …
> fix(mpt): dangling nodes in build_mpt

- .github/workflows/reth-benchmark.yml
- run.sh
Added VM config for Benchmark Compare
https://github.com/axiom-crypto/openvm-reth-benchmark/actions/runs/17507135098
> feat: nsys profile option

- .github/workflows/compare-bench.yml
- .github/workflows/reth-benchmark.yml
- crates/host-bench/src/lib.rs
- run.sh
- runs natively without interpretation
- made it to run always since it takes negligible time
> feat: add `execute-host` execution mode

- .github/workflows/reth-benchmark.yml
- Cargo.lock
- bin/client-eth/Cargo.lock
- run.sh
- remove the arbitrary `- 100` since segments should now be below threshold
> fix: use 2^22 as max trace height
